services:
  api:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./tests/files_to_convert:/home/appuser/app/files_to_convert
      - ./tests/converted_files:/home/appuser/app/converted_files
    command: uvicorn api.main:app --host 0.0.0.0 --port 8000

  worker:
    build: .
    environment:
      - DOCKER_CONTAINER=true
    volumes:               
      - ./tests/files_to_convert:/home/appuser/app/files_to_convert
      - ./tests/converted_files:/home/appuser/app/converted_files
    command: python workers/worker.py
    deploy:
      replicas: 4
    depends_on:
      - api
    restart: on-failure

networks:
  default:
    name: file-converter-network
    